name: ✨ Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much detail as possible.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: "As a student, I want to track my spending habits so I can improve my budgeting..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this feature work?
      placeholder: "Add a 'Spending Tracker' module that allows users to log expenses and categorize them..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other solutions have you considered?
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Critical (blocks major use case)
        - High (important for many users)
        - Medium (nice to have)
        - Low (minor improvement)
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the app should this be added to?
      options:
        - Frontend (Next.js)
        - Backend (NestJS)
        - Database (Prisma)
        - Authentication
        - Payments (Stripe)
        - AI Mentor (Gemini)
        - Gamification
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Wireframes
      description: Upload any mockups or wireframes (optional)
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other relevant information
    validations:
      required: false

  - type: checkboxes
    id: willing_to_contribute
    attributes:
      label: Contribution
      description: Are you willing to contribute this feature?
      options:
        - label: I am willing to submit a pull request for this feature
          required: false
