import React from 'react';

export const Icons = {
    ArrowRight: ({ className }: { className?: string }) => <span className={className}>→</span>,
    Award: ({ className }: { className?: string }) => <span className={className}>🏆</span>,
    BookOpen: ({ className }: { className?: string }) => <span className={className}>📚</span>,
    TrendingUp: ({ className }: { className?: string }) => <span className={className}>📈</span>,
    Users: ({ className }: { className?: string }) => <span className={className}>👥</span>,
    Zap: ({ className }: { className?: string }) => <span className={className}>⚡</span>,
    Shield: ({ className }: { className?: string }) => <span className={className}>🛡️</span>,
    Brain: ({ className }: { className?: string }) => <span className={className}>🧠</span>,
    Play: ({ className }: { className?: string }) => <span className={className}>▶️</span>,
    Star: ({ className }: { className?: string }) => <span className={className}>⭐</span>,
    Sparkles: ({ className }: { className?: string }) => <span className={className}>✨</span>,
    ChevronRight: ({ className }: { className?: string }) => <span className={className}>›</span>,
    Check: ({ className }: { className?: string }) => <span className={className}>✓</span>,
    X: ({ className }: { className?: string }) => <span className={className}>✕</span>,
    Share2: ({ className }: { className?: string }) => <span className={className}>🔗</span>,
    Menu: ({ className }: { className?: string }) => <span className={className}>☰</span>,
    Moon: ({ className }: { className?: string }) => <span className={className}>🌙</span>,
    Sun: ({ className }: { className?: string }) => <span className={className}>☀️</span>,
    LayoutDashboard: ({ className }: { className?: string }) => <span className={className}>📊</span>,
    Home: ({ className }: { className?: string }) => <span className={className}>🏠</span>,
    Settings: ({ className }: { className?: string }) => <span className={className}>⚙️</span>,
    Gamepad2: ({ className }: { className?: string }) => <span className={className}>🎮</span>,
    Trophy: ({ className }: { className?: string }) => <span className={className}>🏆</span>,
    ShoppingBag: ({ className }: { className?: string }) => <span className={className}>🛍️</span>,
    Bell: ({ className }: { className?: string }) => <span className={className}>🔔</span>,
    Globe: ({ className }: { className?: string }) => <span className={className}>🌐</span>,
    Map: ({ className }: { className?: string }) => <span className={className}>🗺️</span>,
    LogOut: ({ className }: { className?: string }) => <span className={className}>🚪</span>,
    User: ({ className }: { className?: string }) => <span className={className}>👤</span>,
} as const;
